/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.overview'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'overview/intro',
    {
      type: 'category',
      label: 'Data Sources',
      items: ['overview/data-sources/intro', 'overview/data-sources/creation'],
    },
    {
      type: 'category',
      label: 'Data Scripts',
      items: ['overview/data-scripts/intro'],
    },
    {
      type: 'category',
      label: 'Trust Mesh',
      items: [
        'overview/trust-mesh/intro',
        'overview/trust-mesh/dataandprofiles',
        'overview/trust-mesh/trustalgorithm',
        'overview/trust-mesh/usersummary',
        'overview/trust-mesh/credentials',
        'overview/trust-mesh/presentations'
      ],
    },
    {
      type: 'category',
      label: 'Assets',
      items: [
        'overview/assets/odin',
        'overview/assets/geo',
        'overview/assets/o9w',
      ],
    },
    {
      type: 'category',
      label: 'Use Cases',
      items: [
        'overview/use-cases/wallace',
      ],
    },
    {/*'overview/ai-tools/intro'^*/ },
  ],

  developSidebar: [
    'develop/intro',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['develop/tutorial-extras/manage-docs-versions', 'develop/tutorial-extras/translate-your-site'],
    },
  ],

};

module.exports = sidebars;
